/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_bienvenue_nutri_choix (void);
GtkWidget* create_modifier_menu (void);
GtkWidget* create_ajouter_menu (void);
GtkWidget* create_Liste_des_menus (void);
