/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_bienvenue_nutri_choix (void)
{
  GtkWidget *bienvenue_nutri_choix;
  GtkWidget *fixed1;
  GtkWidget *label1;
  GtkWidget *button_supp_menu;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label16;
  GtkWidget *button_mod_menu;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label3;
  GtkWidget *button_aj_menu;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label4;
  GtkWidget *button_aff_menu;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label5;
  GtkWidget *button_quit;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label25;

  bienvenue_nutri_choix = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (bienvenue_nutri_choix), _("Bienvenue dans l'espace nutritionniste"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (bienvenue_nutri_choix), fixed1);

  label1 = gtk_label_new (_("Gestion des menus"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 280, 24);
  gtk_widget_set_size_request (label1, 296, 56);
  gtk_misc_set_alignment (GTK_MISC (label1), 0.5, 0.37);

  button_supp_menu = gtk_button_new ();
  gtk_widget_show (button_supp_menu);
  gtk_fixed_put (GTK_FIXED (fixed1), button_supp_menu, 680, 176);
  gtk_widget_set_size_request (button_supp_menu, 136, 42);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_supp_menu), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox8), label16, FALSE, FALSE, 0);

  button_mod_menu = gtk_button_new ();
  gtk_widget_show (button_mod_menu);
  gtk_fixed_put (GTK_FIXED (fixed1), button_mod_menu, 384, 176);
  gtk_widget_set_size_request (button_mod_menu, 128, 42);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_mod_menu), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  button_aj_menu = gtk_button_new ();
  gtk_widget_show (button_aj_menu);
  gtk_fixed_put (GTK_FIXED (fixed1), button_aj_menu, 96, 176);
  gtk_widget_set_size_request (button_aj_menu, 130, 42);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_aj_menu), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  button_aff_menu = gtk_button_new ();
  gtk_widget_show (button_aff_menu);
  gtk_fixed_put (GTK_FIXED (fixed1), button_aff_menu, 392, 360);
  gtk_widget_set_size_request (button_aff_menu, 128, 42);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_aff_menu), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-print-preview", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Consulter"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  button_quit = gtk_button_new ();
  gtk_widget_show (button_quit);
  gtk_fixed_put (GTK_FIXED (fixed1), button_quit, 392, 472);
  gtk_widget_set_size_request (button_quit, 128, 42);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button_quit), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox12), label25, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_supp_menu, "clicked",
                    G_CALLBACK (on_button_supp_menu_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mod_menu, "clicked",
                    G_CALLBACK (on_button_mod_menu_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_aj_menu, "clicked",
                    G_CALLBACK (on_button_aj_menu_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_aff_menu, "clicked",
                    G_CALLBACK (on_button_aff_menu_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_quit, "clicked",
                    G_CALLBACK (on_button_quit_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (bienvenue_nutri_choix, bienvenue_nutri_choix, "bienvenue_nutri_choix");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, label1, "label1");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, button_supp_menu, "button_supp_menu");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, image8, "image8");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, label16, "label16");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, button_mod_menu, "button_mod_menu");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, image2, "image2");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, label3, "label3");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, button_aj_menu, "button_aj_menu");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, image3, "image3");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, label4, "label4");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, button_aff_menu, "button_aff_menu");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, image4, "image4");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, label5, "label5");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, button_quit, "button_quit");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, image12, "image12");
  GLADE_HOOKUP_OBJECT (bienvenue_nutri_choix, label25, "label25");

  return bienvenue_nutri_choix;
}

GtkWidget*
create_modifier_menu (void)
{
  GtkWidget *modifier_menu;
  GtkWidget *fixed2;
  GtkWidget *entry1_jour_a_mod;
  GtkWidget *button6_retour_mod;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label7;
  GtkWidget *label_id_mod;
  GtkWidget *button_rech_mod;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label17;
  GtkWidget *entry_mod_jour;
  GtkWidget *entry_mod_type;
  GtkWidget *entry10;
  GtkWidget *entry_mod_suite;
  GtkWidget *entry_mod_dessert;
  GtkWidget *label_mod_type;
  GtkWidget *label_mod_jour;
  GtkWidget *label_mod_entree;
  GtkWidget *label_mod_suite;
  GtkWidget *label_mod_dessert;
  GtkWidget *button_mod_aff;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label23;

  modifier_menu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_menu), _("Modifier menu "));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (modifier_menu), fixed2);

  entry1_jour_a_mod = gtk_entry_new ();
  gtk_widget_show (entry1_jour_a_mod);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1_jour_a_mod, 328, 88);
  gtk_widget_set_size_request (entry1_jour_a_mod, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_jour_a_mod), 8226);

  button6_retour_mod = gtk_button_new ();
  gtk_widget_show (button6_retour_mod);
  gtk_fixed_put (GTK_FIXED (fixed2), button6_retour_mod, 136, 512);
  gtk_widget_set_size_request (button6_retour_mod, 112, 48);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button6_retour_mod), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox5), label7, FALSE, FALSE, 0);

  label_id_mod = gtk_label_new (_("ID du menu a modifier :"));
  gtk_widget_show (label_id_mod);
  gtk_fixed_put (GTK_FIXED (fixed2), label_id_mod, 8, 88);
  gtk_widget_set_size_request (label_id_mod, 280, 32);

  button_rech_mod = gtk_button_new ();
  gtk_widget_show (button_rech_mod);
  gtk_fixed_put (GTK_FIXED (fixed2), button_rech_mod, 632, 88);
  gtk_widget_set_size_request (button_rech_mod, 136, 34);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_rech_mod), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("rechercher"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox9), label17, FALSE, FALSE, 0);

  entry_mod_jour = gtk_entry_new ();
  gtk_widget_show (entry_mod_jour);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_mod_jour, 208, 200);
  gtk_widget_set_size_request (entry_mod_jour, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mod_jour), 8226);

  entry_mod_type = gtk_entry_new ();
  gtk_widget_show (entry_mod_type);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_mod_type, 200, 280);
  gtk_widget_set_size_request (entry_mod_type, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mod_type), 8226);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed2), entry10, 664, 192);
  gtk_widget_set_size_request (entry10, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  entry_mod_suite = gtk_entry_new ();
  gtk_widget_show (entry_mod_suite);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_mod_suite, 664, 256);
  gtk_widget_set_size_request (entry_mod_suite, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mod_suite), 8226);

  entry_mod_dessert = gtk_entry_new ();
  gtk_widget_show (entry_mod_dessert);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_mod_dessert, 664, 312);
  gtk_widget_set_size_request (entry_mod_dessert, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mod_dessert), 8226);

  label_mod_type = gtk_label_new (_("Type"));
  gtk_widget_show (label_mod_type);
  gtk_fixed_put (GTK_FIXED (fixed2), label_mod_type, 96, 288);
  gtk_widget_set_size_request (label_mod_type, 61, 22);

  label_mod_jour = gtk_label_new (_("Jour"));
  gtk_widget_show (label_mod_jour);
  gtk_fixed_put (GTK_FIXED (fixed2), label_mod_jour, 96, 200);
  gtk_widget_set_size_request (label_mod_jour, 61, 22);

  label_mod_entree = gtk_label_new (_("Entr\303\251e"));
  gtk_widget_show (label_mod_entree);
  gtk_fixed_put (GTK_FIXED (fixed2), label_mod_entree, 560, 192);
  gtk_widget_set_size_request (label_mod_entree, 61, 22);

  label_mod_suite = gtk_label_new (_("Suite"));
  gtk_widget_show (label_mod_suite);
  gtk_fixed_put (GTK_FIXED (fixed2), label_mod_suite, 560, 264);
  gtk_widget_set_size_request (label_mod_suite, 61, 22);

  label_mod_dessert = gtk_label_new (_("Dessert"));
  gtk_widget_show (label_mod_dessert);
  gtk_fixed_put (GTK_FIXED (fixed2), label_mod_dessert, 560, 328);
  gtk_widget_set_size_request (label_mod_dessert, 61, 22);

  button_mod_aff = gtk_button_new ();
  gtk_widget_show (button_mod_aff);
  gtk_fixed_put (GTK_FIXED (fixed2), button_mod_aff, 624, 512);
  gtk_widget_set_size_request (button_mod_aff, 136, 34);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_mod_aff), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-print-preview", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Consulter"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox10), label23, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button6_retour_mod, "clicked",
                    G_CALLBACK (on_button6_retour_mod_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_menu, modifier_menu, "modifier_menu");
  GLADE_HOOKUP_OBJECT (modifier_menu, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (modifier_menu, entry1_jour_a_mod, "entry1_jour_a_mod");
  GLADE_HOOKUP_OBJECT (modifier_menu, button6_retour_mod, "button6_retour_mod");
  GLADE_HOOKUP_OBJECT (modifier_menu, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (modifier_menu, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (modifier_menu, image5, "image5");
  GLADE_HOOKUP_OBJECT (modifier_menu, label7, "label7");
  GLADE_HOOKUP_OBJECT (modifier_menu, label_id_mod, "label_id_mod");
  GLADE_HOOKUP_OBJECT (modifier_menu, button_rech_mod, "button_rech_mod");
  GLADE_HOOKUP_OBJECT (modifier_menu, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (modifier_menu, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (modifier_menu, image9, "image9");
  GLADE_HOOKUP_OBJECT (modifier_menu, label17, "label17");
  GLADE_HOOKUP_OBJECT (modifier_menu, entry_mod_jour, "entry_mod_jour");
  GLADE_HOOKUP_OBJECT (modifier_menu, entry_mod_type, "entry_mod_type");
  GLADE_HOOKUP_OBJECT (modifier_menu, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (modifier_menu, entry_mod_suite, "entry_mod_suite");
  GLADE_HOOKUP_OBJECT (modifier_menu, entry_mod_dessert, "entry_mod_dessert");
  GLADE_HOOKUP_OBJECT (modifier_menu, label_mod_type, "label_mod_type");
  GLADE_HOOKUP_OBJECT (modifier_menu, label_mod_jour, "label_mod_jour");
  GLADE_HOOKUP_OBJECT (modifier_menu, label_mod_entree, "label_mod_entree");
  GLADE_HOOKUP_OBJECT (modifier_menu, label_mod_suite, "label_mod_suite");
  GLADE_HOOKUP_OBJECT (modifier_menu, label_mod_dessert, "label_mod_dessert");
  GLADE_HOOKUP_OBJECT (modifier_menu, button_mod_aff, "button_mod_aff");
  GLADE_HOOKUP_OBJECT (modifier_menu, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (modifier_menu, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (modifier_menu, image10, "image10");
  GLADE_HOOKUP_OBJECT (modifier_menu, label23, "label23");

  return modifier_menu;
}

GtkWidget*
create_ajouter_menu (void)
{
  GtkWidget *ajouter_menu;
  GtkWidget *fixed3;
  GtkWidget *entry_aj_id;
  GtkWidget *entry_aj_jour;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *label_aj_id;
  GtkWidget *label_aj_type;
  GtkWidget *label_aj_jour;
  GtkWidget *label_aj_entree;
  GtkWidget *label_aj_suite;
  GtkWidget *label_aj_dessert;
  GtkWidget *button_ret_aj_menu;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label9;
  GtkWidget *button7_aj_menu;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label8;
  GtkWidget *button_aff_after_aj;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label24;

  ajouter_menu = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_menu), _("Ajouter menu"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (ajouter_menu), fixed3);

  entry_aj_id = gtk_entry_new ();
  gtk_widget_show (entry_aj_id);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_aj_id, 232, 64);
  gtk_widget_set_size_request (entry_aj_id, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_aj_id), 8226);

  entry_aj_jour = gtk_entry_new ();
  gtk_widget_show (entry_aj_jour);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_aj_jour, 232, 184);
  gtk_widget_set_size_request (entry_aj_jour, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_aj_jour), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed3), entry4, 232, 280);
  gtk_widget_set_size_request (entry4, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed3), entry5, 656, 64);
  gtk_widget_set_size_request (entry5, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed3), entry6, 656, 168);
  gtk_widget_set_size_request (entry6, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed3), entry7, 648, 272);
  gtk_widget_set_size_request (entry7, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  label_aj_id = gtk_label_new (_("ID"));
  gtk_widget_show (label_aj_id);
  gtk_fixed_put (GTK_FIXED (fixed3), label_aj_id, 112, 64);
  gtk_widget_set_size_request (label_aj_id, 61, 22);

  label_aj_type = gtk_label_new (_("Type"));
  gtk_widget_show (label_aj_type);
  gtk_fixed_put (GTK_FIXED (fixed3), label_aj_type, 112, 288);
  gtk_widget_set_size_request (label_aj_type, 61, 22);

  label_aj_jour = gtk_label_new (_("Jour"));
  gtk_widget_show (label_aj_jour);
  gtk_fixed_put (GTK_FIXED (fixed3), label_aj_jour, 112, 184);
  gtk_widget_set_size_request (label_aj_jour, 61, 22);

  label_aj_entree = gtk_label_new (_("entr\303\251e"));
  gtk_widget_show (label_aj_entree);
  gtk_fixed_put (GTK_FIXED (fixed3), label_aj_entree, 488, 64);
  gtk_widget_set_size_request (label_aj_entree, 69, 24);

  label_aj_suite = gtk_label_new (_("suite"));
  gtk_widget_show (label_aj_suite);
  gtk_fixed_put (GTK_FIXED (fixed3), label_aj_suite, 488, 168);
  gtk_widget_set_size_request (label_aj_suite, 61, 22);

  label_aj_dessert = gtk_label_new (_("dessert"));
  gtk_widget_show (label_aj_dessert);
  gtk_fixed_put (GTK_FIXED (fixed3), label_aj_dessert, 488, 272);
  gtk_widget_set_size_request (label_aj_dessert, 61, 22);

  button_ret_aj_menu = gtk_button_new ();
  gtk_widget_show (button_ret_aj_menu);
  gtk_fixed_put (GTK_FIXED (fixed3), button_ret_aj_menu, 192, 504);
  gtk_widget_set_size_request (button_ret_aj_menu, 112, 42);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_ret_aj_menu), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox7), label9, FALSE, FALSE, 0);

  button7_aj_menu = gtk_button_new ();
  gtk_widget_show (button7_aj_menu);
  gtk_fixed_put (GTK_FIXED (fixed3), button7_aj_menu, 664, 504);
  gtk_widget_set_size_request (button7_aj_menu, 128, 48);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button7_aj_menu), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Ajouter "));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox6), label8, FALSE, FALSE, 0);

  button_aff_after_aj = gtk_button_new ();
  gtk_widget_show (button_aff_after_aj);
  gtk_fixed_put (GTK_FIXED (fixed3), button_aff_after_aj, 664, 416);
  gtk_widget_set_size_request (button_aff_after_aj, 120, 42);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_aff_after_aj), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-print-preview", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Consulter"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox11), label24, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_ret_aj_menu, "clicked",
                    G_CALLBACK (on_button_ret_aj_menu_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7_aj_menu, "clicked",
                    G_CALLBACK (on_button_aj_menu_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_aff_after_aj, "clicked",
                    G_CALLBACK (on_button_aff_after_aj_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_menu, ajouter_menu, "ajouter_menu");
  GLADE_HOOKUP_OBJECT (ajouter_menu, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (ajouter_menu, entry_aj_id, "entry_aj_id");
  GLADE_HOOKUP_OBJECT (ajouter_menu, entry_aj_jour, "entry_aj_jour");
  GLADE_HOOKUP_OBJECT (ajouter_menu, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (ajouter_menu, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (ajouter_menu, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (ajouter_menu, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (ajouter_menu, label_aj_id, "label_aj_id");
  GLADE_HOOKUP_OBJECT (ajouter_menu, label_aj_type, "label_aj_type");
  GLADE_HOOKUP_OBJECT (ajouter_menu, label_aj_jour, "label_aj_jour");
  GLADE_HOOKUP_OBJECT (ajouter_menu, label_aj_entree, "label_aj_entree");
  GLADE_HOOKUP_OBJECT (ajouter_menu, label_aj_suite, "label_aj_suite");
  GLADE_HOOKUP_OBJECT (ajouter_menu, label_aj_dessert, "label_aj_dessert");
  GLADE_HOOKUP_OBJECT (ajouter_menu, button_ret_aj_menu, "button_ret_aj_menu");
  GLADE_HOOKUP_OBJECT (ajouter_menu, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (ajouter_menu, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (ajouter_menu, image7, "image7");
  GLADE_HOOKUP_OBJECT (ajouter_menu, label9, "label9");
  GLADE_HOOKUP_OBJECT (ajouter_menu, button7_aj_menu, "button7_aj_menu");
  GLADE_HOOKUP_OBJECT (ajouter_menu, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (ajouter_menu, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (ajouter_menu, image6, "image6");
  GLADE_HOOKUP_OBJECT (ajouter_menu, label8, "label8");
  GLADE_HOOKUP_OBJECT (ajouter_menu, button_aff_after_aj, "button_aff_after_aj");
  GLADE_HOOKUP_OBJECT (ajouter_menu, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (ajouter_menu, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (ajouter_menu, image11, "image11");
  GLADE_HOOKUP_OBJECT (ajouter_menu, label24, "label24");

  return ajouter_menu;
}

GtkWidget*
create_Liste_des_menus (void)
{
  GtkWidget *Liste_des_menus;
  GtkWidget *fixed4;
  GtkWidget *treeview1;

  Liste_des_menus = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Liste_des_menus), _("Liste des menus"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Liste_des_menus), fixed4);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview1, 264, 184);
  gtk_widget_set_size_request (treeview1, 300, 200);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Liste_des_menus, Liste_des_menus, "Liste_des_menus");
  GLADE_HOOKUP_OBJECT (Liste_des_menus, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Liste_des_menus, treeview1, "treeview1");

  return Liste_des_menus;
}

